packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/@repo/*'
  - 'packages/comlink/playground'

enablePrePostScripts: true
# TODO why is this needed? Can we use publicHoistPatterns instead?
shamefullyHoist: true
linkWorkspacePackages: deep
preferWorkspacePackages: true

publicHoistPattern:
  - sanity
  - '*eslint*'
  - '*prettier*'
