packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/@repo/*'
  - 'packages/comlink/playground'

catalog:
  '@sanity/assist': ^4.3.0
  '@sanity/color-input': ^4.0.3
  '@sanity/icons': ^3.7.4
  '@sanity/ui': ^2.16.7
  '@sanity/vision': ^3.99.0
  'rxjs': ^7.8.2
  'sanity': ^3.99.0
  'sanity-plugin-asset-source-unsplash': ^3.0.3
  typescript: 5.8.3

catalogs:
  tailwind3:
    '@tailwindcss/typography': ^0.5.16
    tailwindcss: ^3.4.17
